// Polyfill pointer events for Safari <13 and older browsers. Original's
// main.tsx imports this too; without it, pointerdown/move/up on iOS
// <13 fall back to touch events and our handlers stop firing.
// eslint-disable-next-line import/no-unassigned-import
import 'pepjs';
import { mount } from 'svelte';
import AppRoot from './AppRoot.svelte';

// Register the service worker generated by vite-plugin-pwa. Only runs
// in production builds; the dev server uses devOptions.enabled gate.
// vite-plugin-pwa now emits ambient module declarations so the import
// type-checks; @ts-ignore is a defensive no-op for environments where
// the plugin's types aren't bundled (e.g. tsc run outside the Vite
// pipeline).
// @ts-ignore — virtual module injected by vite-plugin-pwa
import { registerSW } from 'virtual:pwa-register';
registerSW({ immediate: true });

// Original Sveltedraw's `SveltedrawFontFace.createUrls` treats raw asset
// paths as relative and needs `window.SVELTEDRAW_ASSET_PATH` to build a
// correct absolute URL. In our Vite dev setup, the font imports resolve
// to `/@fs/C:/.../fonts/Excalifont/...woff2` — an absolute path on THIS
// origin. Setting the base to `location.origin + "/"` makes the resolver
// do `new URL("@fs/C:/...", "http://localhost:3002/")` → the correct
// Vite-served URL. Without this the resolver falls back to esm.sh, which
// yields a dead URL (the errors we saw before this fix).
// Needs to run BEFORE App.svelte mounts so Fonts class reads it at init.
// @ts-ignore — not in lib.dom
window.SVELTEDRAW_ASSET_PATH = window.location.origin + '/';

mount(AppRoot, { target: document.getElementById('app')! });
